/**
 * Advanced Settings Definitions
 * Group: Advanced system configuration and developer settings
 */

import { SettingDefinition } from '../types';

export const advancedSettings: SettingDefinition[] = [
  {
    key: 'advanced.debug_mode',
    label: 'Debug Mode',
    description: 'Enable debug logging and developer tools',
    type: 'policy',
    group: 'advanced',
    defaultValue: false,
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'advanced.performance_monitoring',
    label: 'Performance Monitoring',
    description: 'Enable performance monitoring and metrics collection',
    type: 'policy',
    group: 'advanced',
    defaultValue: false,
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'advanced.error_reporting_url',
    label: 'Error Reporting URL',
    description: 'URL for sending error reports (e.g., Sentry DSN)',
    type: 'policy',
    group: 'advanced',
    defaultValue: '',
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'advanced.api_timeout_seconds',
    label: 'API Timeout (Seconds)',
    description: 'Timeout for API requests in seconds',
    type: 'policy',
    group: 'advanced',
    defaultValue: 30,
    allowedScopes: ['store', 'default'],
    validator: (value: number) => value >= 5 && value <= 300,
    schemaVersion: 1,
  },
  {
    key: 'advanced.cache_enabled',
    label: 'Cache Enabled',
    description: 'Enable client-side caching for improved performance',
    type: 'policy',
    group: 'advanced',
    defaultValue: true,
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'advanced.cache_ttl_minutes',
    label: 'Cache TTL (Minutes)',
    description: 'Time-to-live for cached data in minutes',
    type: 'policy',
    group: 'advanced',
    defaultValue: 60,
    allowedScopes: ['store', 'default'],
    validator: (value: number) => value >= 1 && value <= 1440,
    schemaVersion: 1,
  },
  {
    key: 'localization.language',
    label: 'Language',
    description: 'Application language',
    type: 'preference',
    group: 'advanced',
    defaultValue: 'en',
    allowedScopes: ['user', 'store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'localization.currency',
    label: 'Currency',
    description: 'Currency code (e.g., USD, EUR, GBP)',
    type: 'policy',
    group: 'advanced',
    defaultValue: 'USD',
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'localization.currency_symbol',
    label: 'Currency Symbol',
    description: 'Currency symbol to display',
    type: 'policy',
    group: 'advanced',
    defaultValue: '$',
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'localization.date_format',
    label: 'Date Format',
    description: 'Date format (e.g., MM/DD/YYYY, DD/MM/YYYY)',
    type: 'preference',
    group: 'advanced',
    defaultValue: 'MM/DD/YYYY',
    allowedScopes: ['user', 'store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'localization.time_format',
    label: 'Time Format',
    description: 'Time format (12-hour or 24-hour)',
    type: 'preference',
    group: 'advanced',
    defaultValue: '12',
    allowedScopes: ['user', 'store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'localization.timezone',
    label: 'Timezone',
    description: 'Timezone for date/time display',
    type: 'policy',
    group: 'advanced',
    defaultValue: 'America/New_York',
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
];
