/**
 * Personal Settings Definitions
 * Group: Personal preferences and profile settings
 */

import { SettingDefinition } from '../types';

export const personalSettings: SettingDefinition[] = [
  {
    key: 'user.display_name',
    label: 'Display Name',
    description: 'Your name as it appears in the application',
    type: 'preference',
    group: 'personal',
    defaultValue: '',
    allowedScopes: ['user', 'default'],
    schemaVersion: 1,
    controlType: 'text',
    category: 'Profile',
    placeholder: 'Enter your display name',
  },
  {
    key: 'user.email',
    label: 'Email Address',
    description: 'Your email address for notifications and account recovery',
    type: 'preference',
    group: 'personal',
    defaultValue: '',
    allowedScopes: ['user', 'default'],
    schemaVersion: 1,
    controlType: 'text',
    category: 'Profile',
    placeholder: 'Enter your email address',
  },
  {
    key: 'user.theme_mode',
    label: 'Theme Mode',
    description: 'Choose between light, dark, or automatic theme',
    type: 'preference',
    group: 'personal',
    defaultValue: 'dark',
    allowedScopes: ['user', 'store', 'default'],
    schemaVersion: 1,
    controlType: 'select',
    category: 'Appearance',
    options: [
      { value: 'light', label: 'Light' },
      { value: 'dark', label: 'Dark' },
      { value: 'auto', label: 'Auto (System)' },
    ],
  },
  {
    key: 'user.theme_accent',
    label: 'Accent Color',
    description: 'Choose your preferred accent color',
    type: 'preference',
    group: 'personal',
    defaultValue: 'teal',
    allowedScopes: ['user', 'store', 'default'],
    schemaVersion: 1,
    controlType: 'select',
    category: 'Appearance',
    options: [
      { value: 'teal', label: 'Teal' },
      { value: 'blue', label: 'Blue' },
      { value: 'green', label: 'Green' },
      { value: 'purple', label: 'Purple' },
      { value: 'orange', label: 'Orange' },
      { value: 'red', label: 'Red' },
    ],
  },
  {
    key: 'user.theme_density',
    label: 'Interface Density',
    description: 'Choose between compact, comfortable, or spacious layout',
    type: 'preference',
    group: 'personal',
    defaultValue: 'comfortable',
    allowedScopes: ['user', 'store', 'default'],
    schemaVersion: 1,
    controlType: 'select',
    category: 'Appearance',
    options: [
      { value: 'compact', label: 'Compact' },
      { value: 'comfortable', label: 'Comfortable' },
      { value: 'spacious', label: 'Spacious' },
    ],
  },
  {
    key: 'user.email_notifications',
    label: 'Email Notifications',
    description: 'Receive notifications via email',
    type: 'preference',
    group: 'personal',
    defaultValue: true,
    allowedScopes: ['user', 'default'],
    schemaVersion: 1,
    controlType: 'toggle',
    category: 'Notifications',
  },
  {
    key: 'user.desktop_notifications',
    label: 'Desktop Notifications',
    description: 'Show desktop notifications for important events',
    type: 'preference',
    group: 'personal',
    defaultValue: false,
    allowedScopes: ['user', 'default'],
    schemaVersion: 1,
    controlType: 'toggle',
    category: 'Notifications',
  },
];
