/**
 * Stores & Tax Settings Definitions
 * Group: Store configuration and tax rules
 */

import { SettingDefinition } from '../types';

export const storesTaxSettings: SettingDefinition[] = [
  {
    key: 'store.name',
    label: 'Store Name',
    description: 'The name of this store location',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: '',
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'store.address',
    label: 'Store Address',
    description: 'Physical address of this store',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: '',
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'store.phone',
    label: 'Store Phone',
    description: 'Contact phone number for this store',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: '',
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'store.tax_enabled',
    label: 'Tax Enabled',
    description: 'Enable tax calculations for this store',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: true,
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'store.default_tax_rate',
    label: 'Default Tax Rate',
    description: 'Default tax rate percentage for this store',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: 0,
    allowedScopes: ['store', 'default'],
    validator: (value: number) => value >= 0 && value <= 100,
    schemaVersion: 1,
  },
  {
    key: 'store.tax_name',
    label: 'Tax Name',
    description: 'Display name for tax (e.g., "VAT", "GST", "Sales Tax")',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: 'Tax',
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'store.theme_lock_mode',
    label: 'Lock Theme Mode',
    description: 'Prevent users from changing theme mode',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: false,
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'store.theme_lock_accent',
    label: 'Lock Accent Color',
    description: 'Prevent users from changing accent color',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: false,
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
  {
    key: 'store.theme_lock_contrast',
    label: 'Lock Contrast Mode',
    description: 'Prevent users from changing contrast settings',
    type: 'policy',
    group: 'stores-tax',
    defaultValue: false,
    allowedScopes: ['store', 'default'],
    schemaVersion: 1,
  },
];
